#### Preamble ####
# Purpose: Simulate from Open Data Toronto's statistics on death registration. Link: https://open.toronto.ca/dataset/death-registry-statistics/
# include columns ID, Death Licenses, Civic Centre, Place of Death, Month (as placeholder for date)
# Author: Chloe Thierstein
# Email: chloe.thierstein@mail.utoronto.ca
# Date: 23 January 2023
# Prerequisites: Need to know where to find the City of Toronto death registry data



library(tibble)


simulated_data <-
  tibble(
    #### column 1: Unique ID: generated by random number between 841 
    "ID" = 1:841,
    #### column 2: Death Licenses: generated by random number between 1 and 1000
    "Death Licenses" = runif(n = 841, min = 1, max = 1000),
    #### column 3: Civic Centres: samples 3 centers with size of 841 and it can have duplicates
    "Civic Centre" = sample(
      x = c(
        "Etobicoke",
        "North York",
        "Scarborough"
     ),
     size = 841,
     replace = TRUE
    ),
    #### column 4: place of death: samples 2 options for place of death with size of 841 and it can have duplicates
    "Place of Death" = sample(
      x = c(
        "Toronto",
        "Outside of City Limits"
      ),
      size = 841,
      replace = TRUE
    ),#### column 5: Year: Samples 5 options for year with size of 841 and it can have duplicates
    "Year" = sample(
      x = c(
        "2016",
        "2017",
        "2018",
        "2019",
        "2020"
      ),
      size = 841,
      replace = TRUE
    ),
    #### column 6: month: Samples 12 options for month with size of 841 and it can have duplicates
    "Month" = sample(
      x = c(
        "January",
        "February",
        "March",
        "April",
        "May",
        "June",
        "July",
        "August",
        "September",
        "October",
        "November",
        "December"
      ),
      size = 841,
      replace = TRUE
  )
)
simulated_data

#### testing simulated data ####

#### test 1 #### 

simulated_data$"Civic Centre" |>
  unique() |>
  length() == 3

#### test 2 #### 

simulated_data$"Year" |> min() == 2016

#### test 3 ####

simulated_data$"Death Licenses" |> class() == "numeric"
